# Generated by Django 5.1.7 on 2025-04-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariods16',
            old_name='apelido',
            new_name='biografia',
        ),
        migrations.RenameField(
            model_name='usuariods16',
            old_name='padrinho',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='usuariods16',
            old_name='edv',
            new_name='idade',
        ),
        migrations.RemoveField(
            model_name='usuariods16',
            name='data_nascimento',
        ),
        migrations.AddField(
            model_name='usuariods16',
            name='escolaridade',
            field=models.CharField(choices=[('ENSINO MEDIO', 'Ensino Medio'), ('ENSINO FUNDAMENTAL', 'Ensino Fundamental'), ('ENSINO TECNICO', 'Ensino Tecnico'), ('ENSINO SUPERIOR', 'Ensino superior')], default='Ensino Medio', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariods16',
            name='quant_animal',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariods16',
            name='telefone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
