# Generated by Django 5.1.7 on 2025-04-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0003_alter_usuariods16_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariods16',
            name='quant_animal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
