# Generated by Django 5.2 on 2025-04-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piloto',
            name='classificacao',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
